# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerId: iriszimmermann  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: tryit  # Replace with the name of the image you want to publish


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker-compose -f docs/docker-compose.yml --project-directory . -p docs up -d
        docker wait docs_sut_1
        docker-compose -f docs/docker-compose.yml --project-directory . down
        